### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by bjpritch** [ibm-cloud-docs/secure-enterprise#16]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/secure-enterprise?topic=secure-enterprise-onboard-da#validate-version

### What do you think needs to be updated?

A typo exists:

"For a deployable architcture stack,"

Architecture is mispelled.

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
pull request opened @bjpritch

**Comment by knee-na** [comment]
The typos have been fixed:

- https://cloud.ibm.com/docs/secure-enterprise?topic=secure-enterprise-stack-definition&interface=ui
- https://cloud.ibm.com/docs/secure-enterprise?topic=secure-enterprise-onboard-da&interface=ui#validate-version

Thanks for catching this @bjpritch @Rachad-Alabi-ADEKAMBI
