### ISSUE TITLE
Feedback on "Evaluating an IBM Cloud deployable architecture"

### ISSUE THREAD

**Issue by ocofaigh** [ibm-cloud-docs/secure-enterprise#3]
Doc link: https://cloud.ibm.com/docs/secure-enterprise?topic=secure-enterprise-evaluate-deployable&interface=ui

Step 3.6 was not very clear for me. Suggest change to:

> Use the content source URL to download the source code of the deployable architecture and scan for vulnerabilities.

**Comment by cairey81** [comment]
Hi @ocofaigh! Thanks for the feedback. I've updated our documentation to make that step more clear. You should see the changes soon.
