### ISSUE TITLE
Broken links in Managing Compliance section

### ISSUE THREAD

**Issue by w0o** [ibm-cloud-docs/secure-enterprise#6]
The link "What is a profile?" under first "Important" note and at the last paragraph " in the [Managing Compliance](https://cloud.ibm.com/docs/secure-enterprise?topic=secure-enterprise-onboard-custom&interface=ui#custom-tf-controls) section both lead to a 404.

**Comment by knee-na** [comment]
We've removed the broken links - thank you for catching them!
