### ISSUE TITLE
Broken link on What is an enterprise - Watch and Learn Section.

### ISSUE THREAD

**Issue by teoks** [ibm-cloud-docs/secure-enterprise#7]
HI Team, 

There is broken link for What is an enterprise - Watch and Learn Section.
Thanks.

![WatchLearn](https://github.com/ibm-cloud-docs/secure-enterprise/assets/12643515/c44c4200-7dcb-4ede-b615-ce8b419ed3ad)

**Comment by mekaufman** [comment]
@teoks Thank you for reporting this issue. The video is displaying on the page currently. If you're still experiencing an issue, please reopen this issue.
